### ISSUE TITLE
Homebridge crashes.

### ISSUE THREAD

**Issue by Infi-St** [daymondm/homebridge-vivint#3]
Seems to work fine, but crashes homebridge every few minutes.

0|homebridge  | [17/08/2019, 03:01:20] Homebridge is running on port 42277.
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 21 Data.t: wireless_sensor data.ec: 1058 Data.n: Smoke Detector
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 22 Data.t: wireless_sensor data.ec: 708 Data.n: Smoke Detector - Heat
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 23 Data.t: wireless_sensor data.ec: 556 Data.n: Smoke Detector - Freeze
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 24 Data.t: wireless_sensor data.ec: 1026 Data.n: Carbon Monoxide Detector
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 26 Data.t: wireless_sensor data.ec: 1248 Data.n: Glass Break
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 20003 Data.t: scheduler_service data.ec: undefined Data.n: undefined
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 43 Data.t: energy_service data.ec: undefined Data.n: undefined
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 45 Data.t: network_hosts_service data.ec: undefined Data.n: undefined
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 46 Data.t: panel_diagnostics_service data.ec: undefined Data.n: undefined
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Do not know how to handle device! ID: 47 Data.t: sensor_group data.ec: undefined Data.n: Smoke Detector
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Adding 0 new accessories
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Handling incoming device snapshot for timestamp 2019-08-17T06:59:52.583000
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] Error while bootstrapping accessories
0|homebridge  | [17/08/2019, 03:01:21] [Vivint] TypeError: Cannot read property 'getCharacteristic' of undefined
0|homebridge  |     at MotionSensor.notify (/usr/local/lib/node_modules/homebridge-vivint/lib/device_set.js:334:30)
0|homebridge  |     at MotionSensor.handleSnapshot (/usr/local/lib/node_modules/homebridge-vivint/lib/device_set.js:119:12)
0|homebridge  |     at DeviceSet.handleSnapshot (/usr/local/lib/node_modules/homebridge-vivint/lib/device_set.js:68:44)
0|homebridge  |     at VivintPlatform.Promise.all.then (/usr/local/lib/node_modules/homebridge-vivint/index.js:116:21)
0|homebridge  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|homebridge  | status { category: 'PNConnectedCategory',
0|homebridge  |   operation: 'PNSubscribeOperation',
0|homebridge  |   affectedChannels: [ 'PlatformChannel#9Zcvdw4XvtAxEACmoRYDA8fwWNnTRt-0' ],
0|homebridge  |   subscribedChannels: [ 'PlatformChannel#9Zcvdw4XvtAxEACmoRYDA8fwWNnTRt-0' ],
0|homebridge  |   affectedChannelGroups: [],
0|homebridge  |   lastTimetoken: 0,
0|homebridge  |   currentTimetoken: '15660252815689042' }
0|homebridge  | Error: This callback function has already been called by someone else; it can only be called one time.
0|homebridge  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
0|homebridge  |     at Characteristic.characteristic.on (/usr/local/lib/node_modules/homebridge-vivint/index.js:48:15)
0|homebridge  |     at Characteristic.emit (events.js:194:15)
0|homebridge  |     at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
0|homebridge  |     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
0|homebridge  |     at Array.forEach (<anonymous>)
0|homebridge  |     at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
0|homebridge  |     at HAPServer.emit (events.js:189:13)
0|homebridge  |     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
0|homebridge  |     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
0|homebridge  | [17/08/2019, 03:03:02] Error: This callback function has already been called by someone else; it can only be called one time.
0|homebridge  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
0|homebridge  |     at Characteristic.characteristic.on (/usr/local/lib/node_modules/homebridge-vivint/index.js:48:15)
0|homebridge  |     at Characteristic.emit (events.js:194:15)
0|homebridge  |     at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
0|homebridge  |     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
0|homebridge  |     at Array.forEach (<anonymous>)
0|homebridge  |     at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
0|homebridge  |     at HAPServer.emit (events.js:189:13)
0|homebridge  |     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
0|homebridge  |     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
0|homebridge  | [17/08/2019, 03:03:02] Got SIGTERM, shutting down Homebridge...

**Comment by daymondm** [comment]
Hi, I think I fixed the issue. 

`      if (this.motionBatteryLevelValue()) {`

should be

`      if (this.motionBatteryLevelValue() && this.serviceb) {`

I updated the fork to reflect the changes, please let me know if this fixes the issue you are having. 

Additionally, this error should have only occurred if you've updated the file from a previous version of home bridge-vivint. In order for the battery services to work properly, you will need to delete cached accessories and allow the code to re-add them. This will require some work in terms of re-adding all your accessories in HomeKit so if you wish not to do that then the posted update should allow it to function without battery notifications.

**Comment by Infi-St** [comment]
Deleted my accessories, and did a git pull.. So far no crashes.  Thanks!

**Comment by rob74lee** [comment]
I can't get mine to git pull. This is what I get. Am I doing something wrong?
<img width="1440" alt="Screen Shot 2019-09-05 at 5 30 49 PM" src="https://user-images.githubusercontent.com/34845423/64387887-f591dd00-d002-11e9-8239-5d0a9287db7d.png">

**Comment by daymondm** [comment]
you Need to be in the directory where homebridge-Vivint is installed
